### ISSUE TITLE
Connect with Authorisation Code

### ISSUE THREAD

**Issue by cyriljob** [adplabs/adp-connection-php#3]
Hey,

First of all, thanx for providing the ADP Connection example (sample client made by makeclient.php).
The login/password (MKPLDEMO/marketplace1) for the example seems to no longer be working.
It is denied by the system, am I right ?

Thanx 
Cyril

**Comment by ADPMarketplacePHP** [comment]
Hi Cyril,

I've been told that this has been corrected.  Please let me know if you're still having issues.

**Comment by ADPMarketplace** [comment]
Hi Cyril,

Password for this test user was expired. We updated it back to the old one (marketplace1). This should be working now. Please try now and let us know if you see any issues.

Thanks,
Reddaiah Challa

**Comment by cyriljob** [comment]
Hey,
 
Yep, the login/password issue is solved :-)
Now I'm stuck with the certificates 
 
Message:          Communication Error
Status: 60
Response:        SSL certificate problem: self signed certificate in
certificate chain
 
Probably my fault, but as I use your sample example, I wonder if I have
something special to do.
 
Regarding my customer, I'm afraid to have misunderstood your sentence. When
you say  "please mention the client to reach out to their respective ADP
Account Representative". You mean I have to give you my client name (in that
case it is Diaverum) or if I have to see directly with Diaverum to get their
respective ADP Account Representative ?
 
Thanx again,
Cyril
 
 
  _____

**Comment by ADPMarketplace** [comment]
Hi Cyril,

The client want to reach out to their respective ADP representative for any questions.

Regarding certificates, are you using the provided test certificates against the provided test credentials or you are using it for other credentials in other environment?

Thanks,
Reddaiah Challa

**Comment by cyriljob** [comment]
Hey,
 
I am just trying to run the sample you provide.
So in your code, we can find the path to the certs : 
$ADP_CERTFILE = __DIR__ . "/certs/apiclient_iat.pem";
$ADP_KEYFILE  = __DIR__ . "/certs/apiclient_iat.key";
Of course the certs can be found in my folder at the expected place.
 
I checked the created config array before the call:
$configuration  Array
(
    [grantType] => authorization_code
    [clientID] => ec762f06-7410-4f6d-aa82-969902c1836a
    [clientSecret] => 6daf2cd7-4604-46c0-ab43-a645a6571d34
    [sslCertPath] =>
C:\Apache24\htdocs\hemaRH\client/certs/apiclient_iat.pem
    [sslKeyPath] => C:\Apache24\htdocs\hemaRH\client/certs/apiclient_iat.key
    [tokenServerURL] => https://iat-api.adp.com/
    [scope] => openid
    [responseType] => code
    [redirectURL] => http://localhost:8889/callback
)
 
The server console seems OK :
 

 
But I have this on the browser :

 
Thank You
  _____

**Comment by ADPMarketplace** [comment]
Hi Cyril,

Have you attached any screenshot? We didn't get it here.

Also can you please let us know the version of PHP you are using?

Thanks,
Reddaiah Challa

**Comment by cyriljob** [comment]
Yep
I attached two screenshots.
First was the command log, here it is :
 [Thu Apr  5 14:51:36 2018] [APILOG] Creating class.
[Thu Apr  5 14:51:36 2018] [APILOG] Class created.
[Thu Apr  5 14:51:36 2018] [APILOG] Getting Auth URL
[Thu Apr  5 14:51:36 2018] [APILOG] ::AC building Request URI
[Thu Apr  5 14:51:36 2018] [APILOG] Success!
[Thu Apr  5 14:51:36 2018] [APILOG] URL created.  Redirecting for
authentication.
[Thu Apr  5 14:51:36 2018] 127.0.0.1:52575 [302]:
/connect.php?grant=authorization_code
[Thu Apr  5 14:51:38 2018] [APILOG] Back from authentication.  Received
code.
[Thu Apr  5 14:51:38 2018] [APILOG] Setting class properties.
[Thu Apr  5 14:51:38 2018] [APILOG] Requesting Token.
[Thu Apr  5 14:51:38 2018] [APILOG] ::AC Connect
[Thu Apr  5 14:51:38 2018] [APILOG] ::Building Parameters
[Thu Apr  5 14:51:38 2018] [APILOG] ::Making the call
[Thu Apr  5 14:51:39 2018] [APILOG] ::Checking status
[Thu Apr  5 14:51:39 2018] 127.0.0.1:52599 [200]:
/callback?code=6688adfe-c8f2-4ec1-aa0a-66f236b84cce&state=eee3f963-8619-45d0
-815a-68bda0348907&scope=openid
[Thu Apr  5 14:51:39 2018] 127.0.0.1:52600 [200]: /inc/style.css
[Thu Apr  5 14:51:39 2018] 127.0.0.1:52609 [200]: /inc/logo.png
 
Then it was the error displayed on the browser I already gave you :
You can see the "ADP Marketplace Logo" and the title PHP API Demo, and below
the error message :
"Exception Encountered!
Message:          Communication Error
Status: 60
Response:        SSL certificate problem: self signed certificate in
certificate chain"
 
So as the server console log seems OK, looks like an error in the
callback.php file.
 
I am using PHP 7.0.7
 
Thanx
Cyril
 
  _____

**Comment by ADPMarketplace** [comment]
Hi Cyril,

This doesn't seem to be an issue with the library itself. We were able to successfully use the library without any issue (screencast - http://www.screencast.com/t/1Iconfkl). 

This seems to be a common windows/curl issue. 

Below are few similar issues regarding ssl certificates in general which might be helpful for you -

#1:

https://stackoverflow.com/questions/21187946/curl-error-60-ssl-certificate-issue-self-signed-certificate-in-certificate-cha


There’s a number of reasons he could get the self signed cert error, and in an actual environment (not just in a windows 10 virtual machine), he would need to figure out what exactly is not working.

Theres a hack around it in the above link, but that would be ONLY for testing purposes and would not be left in live code.  Here’s more info:

I am getting curl error 60: SSL certificate problem: self signed certificate in certificate chain on Windows
This is a common issue with latest PHP versions under windows (related to a incompatibility between windows and openssl CAs database).
•	download this CAs database https://curl.haxx.se/ca/cacert.pem to c:/cacert.pem
•	you need to edit your php.ini and add openssl.cafile=c:/cacert.pem (it should point to the file you downloaded)

#2:

A number of customers have reported certificate errors in Windows environments. This is caused by the root certificates on the local machine being out of date. This is similar to problems we've seen in our Ruby client, see ably/ably-ruby#87.
The resolution to this problem is to update your local root certificates to the latest. Follow these instructions:
1 Download the following pem file: http://curl.haxx.se/ca/cacert.pem

2 Copy this file to either c:\cert\cacert.pem (Windows) or any other path on your Unix/ Linux / Mac installation

3 Open php.ini file in your favorite editor

If the following configuration string: curl.cainfo exists in your php.ini, please uncomment it by removing ";" and modify the path in order to point it to the cacert.pem file attached to this e-mail, e.g:

;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

curl.cainfo=c:\cert\cacert.pem

#3:

I assume you're on windows ?
If so this seems to be a very common issue with the cur installation.
Please have a look at these links:
http://stackoverflow.com/questions/9507353/steps-to-setup-curl-in-windows
http://guides.instructure.com/s/2204/m/4214/l/83393-how-do-i-install-and-use-curl-on-a-windows-machine
http://superuser.com/questions/134685/run-curl-commands-from-windows-console
http://www.confusedbycode.com/curl/
http://stackoverflow.com/questions/949959/why-do-64-bit-dlls-go-to-system32-and-32-bit-dlls-to-syswow64-on-64-bit-windows

Thanks,
Reddaiah Challa

**Comment by cyriljob** [comment]
Thanx a lot :-)
 
The workaround worked 
=> 
. download this CAs database  <https://curl.haxx.se/ca/cacert.pem>
https://curl.haxx.se/ca/cacert.pem to c:/cacert.pem
. you need to edit your php.ini and add openssl.cafile=c:/cacert.pem (it
should point to the file you downloaded)
 
The status is now "connected" like on your video.
I guess once connected the use of your REST API  will be easy. There is no
way to test some API online on a test database ?
I suppose I will be able to check that with my customer ADP representative
:-)
 
Thanx again
Cyril
 
  _____

**Comment by ADPMarketplacePHP** [comment]
Cyril,

There is a userinfo call you can download through composer as well, to see an example.  Please note, that the userinfo call only works when authenticating using Authorization Code.  Calling userinfo when authenticating using client credentials will rightfully return an error (invalid scope).

Use our developer portal to see and try sample services in our API explorer:  https://developers.adp.com/articles/api/all

\r
